const categoryList = [
    {
        title: "Electronic Devices",
        keyword: "main category 1",
        subCategory: [{ title: "Mobiles Accessories", keyword: "sub category 1" },
        { title: "Audio", keyword: "sub category 2" },
        { title: "Gadgets", keyword: "sub category 3" },
        { title: "Computers & Laptops Accessories", keyword: "sub category 4" },
        { title: "Computers & Components", keyword: "sub category 5" },
        { title: "Network Components", keyword: "sub category 6" },
        { title: "Console Gaming Accessories", keyword: "sub category 7" },
        { title: "Camera Accessories", keyword: "sub category 8" },
        ],
        toggle: false
    },
    {
        title: "Electronic Accessories",
        keyword: "main category 2",
        subCategory: [{ title: "Mobiles Accessories", keyword: "sub category 1" },
        { title: "Audio", keyword: "sub category 2" },
        { title: "Gadgets", keyword: "sub category 3" },
        { title: "Computers & Laptops Accessories", keyword: "sub category 4" },
        { title: "Computers & Components", keyword: "sub category 5" },
        { title: "Network Components", keyword: "sub category 6" },
        { title: "Console Gaming Accessories", keyword: "sub category 7" },
        { title: "Camera Accessories", keyword: "sub category 8" },
        ],
        toggle: false
    },
    {
        title: "TV & Home Appliances",
        keyword: "main category 3",
        subCategory: [{ title: "TVs & Video Devices", keyword: "sub category 1" },
        { title: "Large Appliances", keyword: "sub category 2" },
        { title: "Small Kitchen Appliamces", keyword: "sub category 3" },
        { title: "Small Cooling & Air treatment", keyword: "sub category 4" },
        { title: "Small Household Appliances", keyword: "sub category 5" },
        { title: "Personal Care Appliances", keyword: "sub category 6" },
        { title: "Parts & Accessories", keyword: "sub category 7" },
        ],
        toggle: false
    },
    {
        title: "Health & Beauty",
        keyword: "main category 4",
        subCategory: [{ title: "Skincare", keyword: "sub category 1" },
        { title: "Make-Up", keyword: "sub category 2" },
        { title: "Hair Care", keyword: "sub category 3" },
        { title: "Bath & Body", keyword: "sub category 4" },
        { title: "Personal Care", keyword: "sub category 5" },
        { title: "Fragrancess", keyword: "sub category 6" },
        { title: "Beauty Tools", keyword: "sub category 7" },
        { title: "Men’s Care", keyword: "sub category 8" },
        { title: "Vitamin & Supplements", keyword: "sub category 9" },
        { title: "Medical Supplies", keyword: "sub category 10" },
        { title: "Adult Diapers & Incontinence", keyword: "sub category 11" },
        { title: "Condoms & Lubricants", keyword: "sub category 12" },
        ],
        toggle: false
    },
    {
        title: "Babies & Toys",
        keyword: "main category 5",
        subCategory: [{ title: "Mother & Baby", keyword: "sub category 1" },
        { title: "Diapering & Potty", keyword: "sub category 2" },
        { title: "Milk Formula & Baby Food", keyword: "sub category 3" },
        { title: "Feeding Essentials", keyword: "sub category 4" },
        { title: "Baby Gear", keyword: "sub category 5" },
        { title: "Nursery", keyword: "sub category 6" },
        { title: "Baby Personal Care", keyword: "sub category 7" },
        { title: "Baby Fashion & Accessories", keyword: "sub category 8" },
        { title: "Toys & Games", keyword: "sub category 9" },
        { title: "Baby & Toddler Toys", keyword: "sub category 10" },
        { title: "Sports Toys & Outdoor Play", keyword: "sub category 11" },
        { title: "Electronic & Remote Controller", keyword: "sub category 12" },
        ],
        toggle: false
    },{
        title: "Groceries & Pets",
        keyword: "main category 6",
        subCategory: [{ title: "Drink", keyword: "sub category 1" },
        { title: "Breakfast Cerals & Spreads", keyword: "sub category 2" },
        { title: "Food Staples & Cooking Essentials", keyword: "sub category 3" },
        { title: "Fruit & Vegetables", keyword: "sub category 4" },
        { title: "Chocolate, Snacks & Sweets", keyword: "sub category 5" },
        { title: "Cleaning Supplies", keyword: "sub category 6" },
        { title: "Laundry Supplies", keyword: "sub category 7" },
        { title: "Pet Accessories", keyword: "sub category 8" },
        { title: "Pet Food", keyword: "sub category 9" },
        { title: "Pet Healthcare", keyword: "sub category 10" },
        ],
        toggle: false
    },    
    {
        title: "Home & Lifestyle",
        keyword: "main category 7",
        subCategory: [{ title: "Lighting", keyword: "sub category 1" },
        { title: "Home Decor", keyword: "sub category 2" },
        { title: "Bedding", keyword: "sub category 3" },
        { title: "Bath", keyword: "sub category 4" },
        { title: "Kitchen & Dining", keyword: "sub category 5" },
        { title: "Stationery & Office Supplies", keyword: "sub category 6" },
        { title: "Laundry & Cleaning", keyword: "sub category 7" },
        { title: "Tool & Home Improvement", keyword: "sub category 8" },
        { title: "Outdoor & Garden", keyword: "sub category 9" },
        { title: "Music & Instruments", keyword: "sub category 10" },
        { title: "Books", keyword: "sub category 11" },
        ],
        toggle: false
    },
    {
        title: "Women's Fashion",
        keyword: "main category 8",
        subCategory: [{ title: "Women’s Clothing", keyword: "sub category 1" },
        { title: "Ligerie, Sleep & Louge", keyword: "sub category 2" },
        { title: "Women’s Shoes", keyword: "sub category 3" },
        { title: "Women’s Watches", keyword: "sub category 4" },
        { title: "Women’s Bags", keyword: "sub category 5" },
        { title: "Women’s Accessories", keyword: "sub category 6" },
        { title: "Women’s Eyewear", keyword: "sub category 7" },
        { title: "Swimwear & Beachwear", keyword: "sub category 8" },
        ],
        toggle: false
    },
    {
        title: "Men's Fashion",
        keyword: "main category 9",
        subCategory: [{ title: "Men's Clothing", keyword: "sub category 1" },
        { title: "Men's Shoes", keyword: "sub category 2" },
        { title: "Men's Watches", keyword: "sub category 3" },
        { title: "Men's Bags", keyword: "sub category 4" },
        { title: "Men's Eyewear", keyword: "sub category 5" },
        { title: "Men's Underwear", keyword: "sub category 6" },
        ],
        toggle: false
    },
    {
        title: "Fashion Accessories",
        keyword: "main category 10",
        subCategory: [{ title: "Bags", keyword: "sub category 1" },
        { title: "Watches", keyword: "sub category 2" },
        { title: "Luggage & Travel", keyword: "sub category 3" },
        { title: "Jewelry", keyword: "sub category 4" },
        { title: "Eyewear", keyword: "sub category 5" },
        { title: "Sunglasses", keyword: "sub category 6" },
        ],
        toggle: false
    },
    {
        title: "Sports & Travel",
        keyword: "main category 11",
        subCategory: [{ title: "Exercise & Fitness", keyword: "sub category 1" },
        { title: "Outdoor Recreation", keyword: "sub category 2" },
        { title: "Sports Apparel", keyword: "sub category 3" },
        { title: "Sports Shoes", keyword: "sub category 4" },
        { title: "Cycling", keyword: "sub category 5" },
        { title: "Water Sports", keyword: "sub category 6" },
        { title: "Team Sports", keyword: "sub category 7" },
        { title: "Racket Sports", keyword: "sub category 8" },
        { title: "Sport Accessories", keyword: "sub category 9" },
        { title: "Travel", keyword: "sub category 10" },
        ],
        toggle: false
    },
    {
        title: "Automotive & Motorcycles",
        keyword: "main category 12",
        subCategory: [{ title: "Oils & Fluids", keyword: "sub category 1" },
        { title: "Automotive", keyword: "sub category 2" },
        { title: "Car Camera", keyword: "sub category 3" },
        { title: "Car Audio", keyword: "sub category 4" },
        { title: "Auto Tires & Wheels", keyword: "sub category 5" },
        { title: "Auto Parts & Spares", keyword: "sub category 6" },
        { title: "Auto Accessories", keyword: "sub category 7" },
        { title: "Car Care", keyword: "sub category 8" },
        { title: "Motorcycle", keyword: "sub category 9" },
        { title: "Moto Tires & Wheels", keyword: "sub category 10" },
        { title: "Moto Parts & Accessories", keyword: "sub category 11" },
        { title: "Motorcycle Riding Gear", keyword: "sub category 12" },
        ],
        toggle: false
    },
]

export default categoryList